server:
    port: 8001
    max-http-header-size: 204800
# 服务名
spring:
    application:
        name: seata-at-ap1
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.104.220.222:8063/seata_demo_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowMultiQueries=true
        username: luojbin
        password: luojbin2@Dev
        hikari:
            maximum-pool-size: 100
            minimum-idle: 10
            #或者修改my.ini character_set_server=utf8mb4
            connection-init-sql: set names utf8mb4
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.luojbin.seata

seata:
    tx-service-group: my_test_tx_group
    registry:
        type: eureka
        eureka:
            service-url: ${eureka.client.service-url.defaultZone}
            application: ${spring.application.name}
            weight: 1
    service:
        vgroup-mapping:
            my_test_tx_group: seata-server

logging:
    level:
        io.seata: debug

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: false